15_rails_authentication/config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :ice_creams
  resources :users, only: [:new, :create, :show]

  get "/login", to: "sessions#new", as: "login"
  post "/login", to: "sessions#create"
  delete "/logout", to: "sessions#destroy"
end

15_rails_authentication/app/models/ice_cream.rb
class IceCream < ApplicationRecord
end

15_rails_authentication/app/models/user.rb
class User < ApplicationRecord
  validates :username, presence: true

  has_secure_password
end

15_rails_authentication/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  helper_method :is_loggedin?, :current_user

  def current_user
    # I will check against the sessions' current user
    # and set it to this instance variable
    if session[:user_id]
      @user = User.find(session[:user_id])
    end
  end

  def is_loggedin?
    # True or false
    !!current_user
  end

  def authorized
    redirect_to login_path unless session[:user_id]
  end
end

15_rails_authentication/app/controllers/ice_creams_controller.rb
class IceCreamsController < ApplicationController
  before_action :authorized, except: [:index]


  def index
      @ice_creams = IceCream.all
      render :index
  end

  def show
    @ice_cream = IceCream.find(params[:id])
    render :show
  end

end

15_rails_authentication/app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    # Find the user
    @user = User.find_by(username: params[:username])
    byebug
    # Making sure they are who they say they are
    if @user && @user.authenticate(params[:password])
      # if the user ***is*** found
      session[:user_id] = @user.id
      redirect_to ice_creams_path
    else
      # If the user isn't found
      redirect_to login_path
    end
  end


  def destroy
    session.delete(:user_id)
    redirect_to login_path
  end
end

15_rails_authentication/app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.create(user_params)

    if @user.valid?
      redirect_to @user
    else
      redirect_to new_user_path
    end
  end

  def show
    @user = User.find(params[:id])
    render :show
  end

  private
  def user_params
    params.require(:user).permit(:username, :password)
  end
end

15_rails_authentication/app/views/ice_creams/index.html.erb
<% @ice_creams.each do |ice_cream| %>
  <p><%= link_to ice_cream.flavor, ice_cream_path(ice_cream) %></p>
<% end %>

15_rails_authentication/app/views/ice_creams/show.html.erb
<%= @ice_cream.flavor %>

15_rails_authentication/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>FlatironIcecreamParlour</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <h1>Prince's cool app</h1>
    <!--  If logged in, show logout -->
    <%  if current_user %>
      <%= form_tag "/logout", method: :delete do %>
          <%= submit_tag "Logout" %>
      <% end %>
    <!-- If not logged in, show login -->
    <% else %>
      <%= link_to "log in", login_path %>
    <% end %>
    <%= yield %>
  </body>
</html>

15_rails_authentication/app/views/users/new.html.erb
<h2>Sign up to Flatiron IceCream Parlourrrrrrrr</h2>
<%= form_for @user do |f| %>
  <%= f.label :username %>
  <%= f.text_field :username %>
  <%= f.label :password %>
  <%= f.text_field :password %>
  <%= f.submit "Sign up" %>
<% end %>

15_rails_authentication/app/views/users/show.html.erb
<%= @user.username %>